INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Uncategorized');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Automotive Expenses');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Charitable Giving');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Child/Dependent Expenses');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Clothing/Shoes');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Education');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Entertainment');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Gasoline/Fuel');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Gifts');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Groceries');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Healthcare/Medical');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Home Maintenance');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Home Improvement');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Insurance');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Cable/Satellite Services');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Online Services');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Loans');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Mortgages');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Other Expenses');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Personal Care');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Rent');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Restaurants/Dining');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Travel');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Service Charges/Fees');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'ATM/Cash Withdrawals');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Checks');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Hobbies');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Other Bills');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Taxes');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Telephone Services');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Utilities');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Pets/Pet Care');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Electronics');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'General Merchandise');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Office Supplies');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Advertising');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Business Miscellaneous');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Postage and Shipping');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Printing');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Dues and Subscriptions');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Office Maintenance');
INSERT INTO `cards`.`Category` (`idCategory`, `name`) VALUES (NULL, 'Wages Paid');
