DROP PROCEDURE IF EXISTS MerchantGetEmpty;

DELIMITER //

CREATE PROCEDURE MerchantGetEmpty()
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
  SELECT 
    NULL AS idMerchant, 
    NULL AS idCategory,
    NULL AS name,
    NULL AS nameCategory;
END
//

DELIMITER ;